# Generated by Django 5.0.1 on 2024-01-10 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerceapp', '0002_userdetails_alter_products_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='token',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
